epoch: 300

LearningRate:
  base_lr: 0.02
  schedulers:
  - !CosineDecay
    max_epochs: 300
  - !LinearWarmup
    start_factor: 0.001
    steps: 1000

OptimizerBuilder:
  clip_grad_by_norm: 1.0
  optimizer:
    type: Momentum
    weight_decay: 0.0001
    momentum: 0.9