_BASE_: [
  '../datasets/coco_detection.yml',
  '../runtime.yml',
  '_base_/optimizer_1x.yml',
  '_base_/efficientdet_d0.yml',
  '_base_/efficientdet_reader.yml',
]

snapshot_epoch: 3
weights: output/efficientdet_d0_1x_coco/model_final